config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  resources :checkouts
  resources :locations
  resources :homes
  get 'homes/index', :controller=>'home', :action=>'title'

  patch 'appointments/update'
  root to: "patients#new"
  devise_for :users
  resources :searches
  resources :doctors
  resources :patients
  resources :checkouts, only: [:new, :create, :show]

  resources :appointments do
    member do
      put :confirmation
    end
  end


end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments, source: :patient  	
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]
  before_action :is_admin?

  def index
    @doctors = Doctor.paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def new
    @doctor = Doctor.new
  end

  def edit; end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to @doctor, notice: 'Doctor was successfully created.' 
    else
      render :new 
    end
	end

  def update
    if @doctor.update(doctor_params)
      redirect_to @doctor, notice: 'Doctor was successfully updated.' 
    else
      render :edit 
    end
  end 

  def destroy
    @doctor.destroy
    redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' 
  end

  private 

    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    def doctor_params
      params.require(:doctor).permit(:name, :designation)
    end

    def is_admin?
      redirect_to new_patient_path unless current_user.admin
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/edit.html.erb
<% provide(:title, "Edit doctor") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@doctor) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :designation %>
      <%= f.text_field :designation %>

      <%= f.time_select :timing,
			{ampm: true,
			ignore_date: true,
			start_hour: 10, 
			end_hour: 18,
			discard_minute: true,
			prompt: true,
			prompt: { hour: "Choose hr" }
			} %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>


  </div>
</div>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Doctors</h1>

<div class="table-responsive">          
 <table class="table table-bordered"> 
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<% provide(:title, 'Sign up') %>
<h3>Register</h3>

<div class="column">
  <div class="form-group">
    <%= form_for(@doctor) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control" %>

      <%= f.label :designation %>
      <%= f.text_field :designation, class:"form-control"  %>

      <%= f.time_select :timing,
{ampm: true,
ignore_date: true,
start_hour: 10, 
end_hour: 18,
discard_minute: true,
prompt: true,
prompt: { hour: "Choose hr" }
} %>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>