config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  resources :checkouts
  resources :locations
  resources :homes
  get 'homes/index', :controller=>'home', :action=>'title'

  patch 'appointments/update'
  root to: "patients#new"
  devise_for :users
  resources :searches
  resources :doctors
  resources :patients
  resources :checkouts, only: [:new, :create, :show]

  resources :appointments do
    member do
      put :confirmation
    end
  end


end

app/models/checkout.rb
class Checkout < ApplicationRecord
end

app/controllers/checkouts_controller.rb
require 'checkout_decorator'
class CheckoutsController < ApplicationController
  before_action :set_checkout, only: [:show, :edit, :update, :destroy]

  # GET /checkouts
  # GET /checkouts.json
  def index
    @checkouts = Checkout.all
  end

  # GET /checkouts/1
  # GET /checkouts/1.json
  def show
  end

  # GET /checkouts/new
  def new
    @checkout = Checkout.new
  end

  # GET /checkouts/1/edit
  def edit
  end

  # POST /checkouts
  # POST /checkouts.json
  def create
    #@checkout = Checkout.new(checkout_params)
    @checkout = Checkout.new()
    @checkout.treatment = params[:checkout][:treatment]
    @checkout.cost = params[:checkout][:cost]
    # @car.color = params[:car][:color]
    # @car.manufacturer = params[:car][:manufacturer]

    myCheckout = BasicCheckout.new(30, @checkout.treatment)
    # add the extra features to the new car
    if params[:checkout][:windows].to_s.length > 0 then
      myCheckout = ElectricWindowsDecorator.new(myCheckout)
    end
    if params[:checkout][:mirror].to_s.length > 0 then
      myCheckout = MirrorDecorator.new(myCheckout)
    end
    if params[:checkout][:psensor].to_s.length > 0 then
      myCheckout = ParkingSensorDecorator.new(myCheckout)
    end

    ## populate the cost and the description details
    @checkout.cost = myCheckout.cost
    #@checkout.description = myCheckout.details


    respond_to do |format|
      if @checkout.save
        format.html { redirect_to @checkout, notice: 'Checkout was successfully created.' }
        format.json { render :show, status: :created, location: @checkout }
      else
        format.html { render :new }
        format.json { render json: @checkout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checkouts/1
  # PATCH/PUT /checkouts/1.json
  def update
    respond_to do |format|
      if @checkout.update(checkout_params)
        format.html { redirect_to @checkout, notice: 'Checkout was successfully updated.' }
        format.json { render :show, status: :ok, location: @checkout }
      else
        format.html { render :edit }
        format.json { render json: @checkout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkouts/1
  # DELETE /checkouts/1.json
  def destroy
    @checkout.destroy
    respond_to do |format|
      format.html { redirect_to checkouts_url, notice: 'Checkout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checkout
      @checkout = Checkout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def checkout_params
      params.require(:checkout).permit(:treatment, :cost)
    end
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/views/checkouts/_form.html.erb
<%= form_with(model: checkout, local: true) do |form| %>
  <% if checkout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(checkout.errors.count, "error") %> prohibited this checkout from being saved:</h2>

      <ul>
      <% checkout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :treatment %>
    <%= form.text_field :treatment %>
  </div>


  <div class="field">
    Basic Checkup:
    <%= check_box_tag 'checkout[windows]', 'windows' %>
  </div>
  <div class="field">
    Advance Checkup:
    <%= check_box_tag 'checkout[mirror]', 'mirror' %>
  </div>
  <div class="field">
    Eyesight:
    <%= check_box_tag 'checkout[psensor]', 'psensor' %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/checkouts/edit.html.erb
<h1>Editing Checkout</h1>

<%= render 'form', checkout: @checkout %>

<%= link_to 'Show', @checkout %> |
<%= link_to 'Back', checkouts_path %>

app/views/checkouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Checkouts</h1>

<table>
  <thead>
    <tr>
      <th>Treatment</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @checkouts.each do |checkout| %>
      <tr>
        <td><%= checkout.treatment %></td>
        <td><%= checkout.cost %></td>
        <td><%= link_to 'Show', checkout %></td>
        <td><%= link_to 'Edit', edit_checkout_path(checkout) %></td>
        <td><%= link_to 'Destroy', checkout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Checkout', new_checkout_path %>

app/views/checkouts/new.html.erb
<h1>New Checkout</h1>

<%= render 'form', checkout: @checkout %>

<%= link_to 'Back', checkouts_path %>

app/views/checkouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Treatment:</strong>
  <%= @checkout.treatment %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @checkout.cost %>
</p>

<%= link_to 'Edit', edit_checkout_path(@checkout) %> |
<%= link_to 'Back', checkouts_path %>