config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  resources :checkouts
  resources :locations
  resources :homes
  get 'homes/index', :controller=>'home', :action=>'title'

  patch 'appointments/update'
  root to: "patients#new"
  devise_for :users
  resources :searches
  resources :doctors
  resources :patients
  resources :checkouts, only: [:new, :create, :show]

  resources :appointments do
    member do
      put :confirmation
    end
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hospital Appointment System</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header class="navbar navbar-fixed-top navbar-inverse ">
    <div class="container">
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", homes_index_path %></li>
          <li><%= link_to "Doctor", new_doctor_path %></li>
          <li><%= link_to "Patient", new_patient_path %></li>
          <li><%= link_to "Find nearest hospital", new_location_path %></li>
          <li><%= link_to "See Appointments", appointments_path %></li>
        </ul>
          <ul class="nav navbar-nav navbar-left">
            <% if user_signed_in? %>
              <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |</li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
              <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
            <% end %>
          </ul>
      </nav>
    </div>
  </header>

  <body>

   <!sign up>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <nav>
    <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
    <% end %>
    </p>
  </nav>
    <%= yield %>
  </body>
    <footer>
      <p><%= image_tag("background5.png", size: "1310x310", :alt => "rss feed", :style => "float :center; border 1px solid #00000;", :class=> 'circular-image') %> </p>
    </footer>
</html>